### PR TITLE
added the preprocessing code 

### PR DESCRIPTION
**Pull request by Heartz00**
We have reformatted the data and made it ready for the EDA team

### CODE REVIEW

**Comment by Carol-Kelly** [comment]
@Heartz00  I have checked the notebook, you didn't indicate the shape of the dataset

**Comment by Carol-Kelly** [comment]
@Heartz00  I have checked the notebook, you didn't indicate the shape of the dataset

**Comment by Heartz00** [comment]
i did , check where i wrote there are 14 rows and...

**Comment by Heartz00** [comment]
> @Heartz00 I have checked the notebook, you didn't indicate the shape of the dataset

line 4

**Comment by Duks31** [comment]
Code Looks Ok 👌

**Comment by Lehita** [comment]
The years are column names....

**Comment by Carol-Kelly** [comment]
Well done

**Pull request closed without merging**
